/**
 * This file aggregates all processor factories
 * Auto-generated by codegen - DO NOT EDIT MANUALLY
 */

import {
  type ProcessorRecord,
  type IProcessorHostModule,
} from "document-drive/processors/types";

// Import other processor factories here as they are generated
import { todoIndexerProcessorFactory } from "./todo-indexer/factory.js";

export const processorFactory = (module: IProcessorHostModule) => {
  // Initialize all processor factories once with the module
  const factories: Array<(driveId: string) => Promise<ProcessorRecord[]>> = [];

  // Add all processor factories

  // Add other processors here as they are generated
  factories.push(todoIndexerProcessorFactory(module));

  // Return the inner function that will be called for each drive
  return async (driveId: string): Promise<ProcessorRecord[]> => {
    const processors: ProcessorRecord[] = [];

    // Call each cached factory with the driveId
    for (const factory of factories) {
      const factoryProcessors = await factory(driveId);
      processors.push(...factoryProcessors);
    }

    return processors;
  };
};
